
name: "YYAGI2_SP"
tags: ["SP", "YYAGI", "PB"]

packetbeat.interfaces.device: enp41s0

packetbeat.flows:
  timeout: 30s
  period: 10s

packetbeat.protocols:
- type: dns
  ports: [53]

- type: http
  ports: [80, 8080, 8000, 5000, 8002]

- type: tls
  ports: [443, 993, 995, 5223, 8443, 8883, 9243]
        

output.elasticsearch:
  hosts: ["https://elastic.joystreamstats.live:443"]
  protocol: "https"
  #api_key: "MHJ6bVhvRUJybmlHM2NJSC16cmw6OE1CMmdpeXFSaTZjR1B0M3cxeFBfQQ=="
  username: "beats_admin"
  password: "*********"
#setup.kibana:
  #host: "https://kibana.yyagi.cloud"
  #username: "beats_admin"
  #password: "L3tM31n!"
#   protocol: "https"
#   ssl.enabled: false
#   ssl.certificate_authorities: ["/usr/share/packetbeat/certs/ca/ca.crt"]

xpack.monitoring.enabled: true
